---
title: "Begin With Bayes: Assessing a Decision Theoretic and Probabilistic Approach to Statistics and Machine Learning Instruction"
author: 
  - name: "Marc Dotson"
    affiliation: "Utah State University"
    email: "marc.dotson@usu.edu"
  - name: "Reagan Siggard"
    affiliation: "Utah State University"
    email: "reagan.siggard@usu.edu"
  - name: "Tyler Brough"
    affiliation: "Utah State University"
    email: "tyler.brough@usu.edu"
date: "July 31, 2026"
abstract: | 
  The framing and depth of statistics and machine learning instruction varies widely. These differences rightly depend on the specifics of the field in which statistics and machine learning is applied, aligning instruction and existing student understanding. However, in settings where students don't have a common application, statistics and machine learning instruction and existing student understanding can be misaligned. In this paper, we propose using decision theory and probability as a general, unifying perspective to statistics and machine learning instruction. We evaluate the impact of this approach on business school student confidence and understanding in an interdiscplinary setting.
keywords:
  - "Bayesian Inference"
  - "Decision Theory"
  - "Machine Learning Instruction"
  - "Pedagogy"
  - "Probabilistic Machine Learning"
  - "Probability"
  - "Statistics Instruction"
bibliography: references.bib
format: 
  jasa-pdf: 
    keep-tex: true
    cite-method: natbib
    journal:
      blinded: false
execute:
  echo: false
---

## Introduction {#sec-intro}

Statistics and machine learning instruction varies in technical depth conditional on the departmental home of the course, the discipline of the instructor, and the needs of the students. This variation has proliferated with the advent of data science, business intelligence, and other jobs. Statistics and machine learning instruction also varies in framing. Though less of a consideration than depth and often assumed away or made implicit, framing statistics and machine learning with descriptive, predictive, computational, inferential, or other perspectives can have a significant impact on student understanding and confidence in using these tools in practice, particularly in applied disciplines. In this paper, we propose using decision theory and probability as a general, unifying perspective for statistics and machine learning instruction. We evaluate the impact of this approach on business school student confidence and understanding in an interdiscplinary setting.

### Decision Theory

Decision theory is a principled, unifying framework for decision making under uncertainty. While we can and should provide a variety of business "cases" to illustrate applications, we can't cover every possible application. Decision theory facilitates the generalization of a principled approach to any kind of application. It also helps embed data analysts in the details of the business problem so they can better communicate the implications of their analysis to the decision makers. While computer science and statistics have long been seen as central to the field of machine learning, decision theory brings economics squarely into the fold. While decision theory is clearly not used in every discipline, it *can* be used in every discipline and provides the heart of the automated feedback loop in reinforcement learning. This framework can both help differentiate our students and improve the practice of data analytics and machine learning and emphasize the importance of keeping a human in the loop as part of any decision-making process.

To illustrate how decision theory can be used, let’s consider a canonical marketing application of deciding on how to set optimal prices. In the presence of uncertainty about heterogeneity in consumer preferences and price sensitivity, businesses actively price discriminate through targeted promotional offers (e.g., coupons). As a data analyst communicates with domain experts to understand the problem and how to inform the decision, a decision theoretic approach requires specifying an objective function that is consistent with the problem and captures the risk aversion of the decision maker. For this problem, a simple customer-specific profit function suffices:

$$
\pi(p) = Y(p) \times (p – mc)
$$

where $p$ is the personalized price for the given customer, $Y(p)$ is the predicted demand for the given customer, and $mc$ is the marginal cost. In decision theory, the objective function is typically a loss function. We can identify an optimal decision, conditioned on the specification of the objective function, by minimizing the loss function or, as we have here, maximizing a utility or profit function.

After working with domain experts to specify an objective function, we quantify uncertainty about heterogeneity in consumer preferences and price sensitivity by modeling demand. Additionally, as with any modeling application, we end up comparing models. Instead of comparing models using in-sample fit or even out-of-sample, predictive fit -- with decision theory, we compare models based on the specified objective function that directly relates to the decision we're trying to inform. This decision-theoretic approach results in the selection of models (and estimators) that differ widely from those that would be selected using a purely statistical approach.

- See @smith_optimal_2023 for more details on this example.
- See @giocoli_wald_2013 for the history of decision theory.
- See @kennedy_teaching_1998 for an econometric perspective.

### Probability

A probabilistic approach to machine learning enhances the principled, unifying framework provided by decision theory. Using probability in association with decision theory naturally leads to Bayesian statistics, where we treat all unknowns as random variables and can directly use probability distributions to quantify uncertainty in our estimates. We can also employ frequentist statistics, where we treat data as random and indirectly use probability distributions to quantify uncertainty in our estimates, but it is best understood as an approximation to the full probabilistic, Bayesian approach. The direct, Bayesian approach is arguably more intuitive, especially for applied students, while the indirect, frequentist approach is less computationally intensive. The hope is that introducing them in contrast and as complements will enhance student understanding of modeling generally and combat the problem of student overfitting to a set list of procedures.

- See @murphy_probabilistic_2022 for more details on this approach.
- See @strumbelj_past_2024 for a discussion on computational tools.

## Study {#sec-study}

In this study, we seek to measure the impact of employing an approach to machine learning instruction tailored to applied and interdisciplinary students. Specifically, we are interested in exploring whether a decision theoretic and probabilistic approach to machine learning improves business student confidence in and understanding of using machine learning in practice.

### Steps

#### Collecting Data

1. The students will receive the invitation to participate in the research via the Recruiting Announcement on their Canvas course. (Reagan Siggard will post this in the in person and online course.)
2. The students will or will not complete the informed consent that is housed on Reagan Siggard's Qualtrics Survey account.
3. All students will complete the pre-class survey.
4. All students will complete the post-class survey.
5. The Qualtrics survey will be housed within Reagan's Qualtrics account so the PI is unable to view who consented to the survey.
6. Reagan will compile the list of students who participated and those who chose the alternative extra credit assignment. Reagan will share this list with the course instructors at the end of the semester. It will not be distinguishable as to which students participated in the research and who chose the alternative option. The instructors will then add the extra credit.
7. After the class has concluded, all data from the pre- and post-survey will be downloaded (identifiable), and those students who opted out of the study responses will be removed.
8. After the class has concluded, only student outcome data (grades, assignments, etc.) of those who participated in the study will be downloaded (identifiable) and uploaded to a USU Box folder.
9. We will replace names with a pseudonym and a-numbers will be removed from the survey data.
10. The research team will store all data in a USU Box folder only shared amongst the research team.

#### Evaluating Responses

1. Download the pre- and post-survey data (Spring 2025, Fall 2025, and Spring 2026) and flag the students who *opted into* the study.
2. Create a dataset combining the responses from both the pre- and post-surveys from both semesters where each row contains a student rating and open-ended response to one of the seven research questions from either the pre- or post-survey and the columns are the student ID, the semester they took the class, whether the response is from the pre- or post-survey, the flag for students who opted into the study, any demographic information (e.g., major, age, gender), the research question ID, the student rating of their confidence in understanding the concept associated with the research question, and the open-ended response to the research question.
3. Generate a column of randomized, anonymous identifiers and randomize the order of the observations *within* each research question. Create a blinded dataset for evaluation by selecting only the anonymous identifier, the research question ID, and the open-ended response to the research question. Evaluators of the resulting dataset are blind to the student, the semester they took the class, whether the open-ended response is from the pre- or post-survey, whether the student opted into the study, and any demographic information.
4. Evaluators will rate the open-ended responses using the same rating scale that students used to evaluate their confidence that they understand the concepts. They will also utilize AI to replicate the same evaluation. Specifically, evalutors will rate how well the response indicates the student understands the concept associated with the question using the following scale: 1. No Understanding; 2. Slight Understanding; 3. Some Understanding; 4. Fair Understanding; 5. Complete Understanding.
5. Evaluator (and AI) ratings will be joined back to the original dataset using the anonymous identifer where they can be averaged, contrasted, and compared between semesters, pre- and post-survey responses, by overall and study participation, and using demographics.
6. Remove pre- and post-survey data for any students who *didn't opt into* the study, download their outcome data (grades, assignments, etc.), and store in a USU Box folder.

### Questions

- How confident are you that you understand what machine learning is?
- In your own words, please describe as simply as possible what machine learning is.
- How confident are you that you understand why we use machine learning?
- In your own words, please describe as simply as possible why we use machine learning.
- How confident are you that you understand how machine learning can be used to inform business decisions?
- In your own words, please describe as simply as possible how machine learning can be used to inform business decisions.
- How confident are you that you understand the role of uncertainty in machine learning and its use in informing business decisions?
- In your own words, please describe as simply as possible the role of uncertainty in machine learning and its use in informing business decisions.
- How confident are you that you understand when we need to use models that are interpretable?
- In your own words, please describe as simply as possible when we need to use models that are interpretable.
- How confident are you that you understand how to communicate the results of models in terms of business insights?
- In your own words, please describe as simply as possible how you would communicate the results of a model in terms of business insights.
- How confident are you in your ability to use machine learning to inform business decisions in practice?
- In your own words, please describe in detail one way in which you would use machine learning to inform a business decision in practice.
- Considering what you know now, what are the most pressing questions you have about using machine learning in practice?
- Section, major, age, and gender as demographics.
